server:
  port: 9090

spring:
  application:
    name: ms-supplier
  datasource:
    url: jdbc:mysql://mysql:3306/supplier-db?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

custom:
  message: config repo ml
